_Complex float Cf(complex * z)65 *f__rp__rpow_ui(*(__x))
#define d_float(__x) (sqrt(*(__x))
#define r_sign(__a,__b) ((__b) >= 0? ((__a) >= 0? (__a) : -(__a)) : -((__a) >= 0? (__a) : -(__a)))
#define d_sign(a,b) u_sign(*(a),*(b))
#define r_sign(a,b) u_sign(*(a),*(b))
#define d_sin(x) (sin(*(x)))
#define d_sinh(x) (sinh(*(x)))
#define d_sqrt(x) (sqrt(*(x)))
#define d_tan(x) (tan(*(x)))
#define d_tanh(x) (tanh(*(x)))
#define i_abs(x) abs(*(x))
#define i_dnnt(x) ((integer)u_nint(*(x)))
#define i_